<?php

namespace App\Http\Services\hotelAPI;

use Illuminate\Support\Facades\Http;
use SoapClient;

class Hotelbeds
{
    /**
     * @param  \Illuminate\Http\Request  $request
     * @return string|null
     * NOTE: Please note that the API keys provided with registration will only give you access to our evaluation environment, with a limited allowed quota of 50 requests per day. If the quota is exceeded you will receive a 403 error
     * 
     */
    //     $request = new http\Client\Request("POST",
    //     $endpoint,
    //     [ "Api-Key"     => $apiKey,
    //       "X-Signature" => $signature,
    //       "Accept"      => "application/xml" ],
    //    $xml);

    public function acc_auth()
    {
        $client = new \GuzzleHttp\Client();

        $apiKey = "4e60b878b1fb4dc10f453884e102413c";
        $secret = "84dc9fafc2";

        // Signature is generated by SHA256 (Api-Key + Shared Secret + Timestamp (in seconds))
        $signature = hash("sha256", $apiKey . $secret . time());

        $headers = [
            'Content-Type' => 'application/json',
            'Accept' => 'application/json',
            'Api-key' => $apiKey,
            'X-Signature' => $signature,
        ];

        $apiURL = 'https://api.test.hotelbeds.com/hotel-api/1.0/status';

        $res = $client->request('GET', $apiURL, [
            'headers' => $headers,
        ]);

        $statusCode = $res->getStatusCode();
        $responseBody = json_decode($res->getBody(), true);

        return $responseBody;
    }
}